In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('iitk_course.csv')

In [4]:
df

         Student Name  Course  Marks (%)  Attendance (%)
0         Dipon Konar  ELC111      56.72           63.08
1      Parth Parashar  PHY113      84.59           20.96
2         Anurag Sahu  MTH113      41.13           59.86
3    Hemakshi Kumawat  CHM112      59.43           57.34
4      Parth Parashar  ELC111      62.88           30.82
..                ...     ...        ...             ...
195     Kritika Singh  ELC112      68.57           77.98
196   Harshit Karnani  PHY112      52.31           35.75
197       Sneha Patra  PHY113      58.98           21.98
198       Ashma Singh  PHY111      88.56           82.63
199    Parth Parashar  PHY115      80.52           42.89

[200 rows x 4 columns]

In [5]:
print(df.to_string())

           Student Name  Course  Marks (%)  Attendance (%)
0           Dipon Konar  ELC111      56.72           63.08
1        Parth Parashar  PHY113      84.59           20.96
2           Anurag Sahu  MTH113      41.13           59.86
3      Hemakshi Kumawat  CHM112      59.43           57.34
4        Parth Parashar  ELC111      62.88           30.82
5      Nikhil Prajapati  LIF111      50.92           84.25
6          Prince Singh  MTH111      66.27             NaN
7           Gungun Jain  PHY111      57.53           42.08
8      Nikhil Prajapati  ELC112      74.09           58.68
9              Siva Sai  PHY111      84.92           53.99
10       Manisha Rathod  PHY114      62.63           69.32
11     Hemakshi Kumawat  CHM113      80.87           34.85
12         Pratik Maity  CHM111        NaN           66.10
13   Praneel iralapalle  PHY115      65.80           61.74
14             Siva Sai  ELC113      56.81           66.56
15       Siddharth Soni  CHM113      68.58           41.27
16             Siva Sai  ELC111      51.63           46.43
17         Anusha Gupta  ELC113      53.50           21.59
18         Prince Singh     NaN      86.64           68.88
19   Praneel iralapalle  ELC113      81.38           86.72
20          Sneha Patra  ELC112      42.91           32.53
21             Siva Sai  ELC112      85.76           86.21
22         Anusha Gupta  PHY115      59.77             NaN
23               Chhaya  MTH113      80.12           66.81
24                  NaN  MTH113      82.35           74.85
25       Siddharth Soni  ESC112      80.06           79.10
26         Anurag Patil  CHM111      43.33           45.83
27          Sejal Dubey  LIF111      41.10           39.85
28     Nikhil Prajapati  PHY115        NaN           50.90
29       Kanishk Sharma  PHY111      78.67           49.48
30          Dipon Konar  PHY112      83.43             NaN
31          Dipon Konar  PHY112      59.30           64.41
32         Anusha Gupta  MTH112      43.18           20.12
33       Riddhi Shingte  PHY111      89.85           40.21
34          Sejal Dubey  PHY111      42.17           23.14
35         Prince Singh  LIF111      61.50           52.04
36               Chhaya  PHY115      65.92           30.84
37         Anurag Patil  PHY111      87.75           39.91
38          Dipon Konar  CHM113      50.74             NaN
39       Manisha Rathod  CHM113      63.06           33.77
40          Sneha Patra  ESC111      49.92           75.94
41               Chhaya  PHY114      51.58           64.92
42       Riddhi Shingte     NaN      46.87           66.51
43      Harshit Karnani  PHY115      42.65           88.23
44     Hemakshi Kumawat  MTH114        NaN           49.58
45       Aryaman Oberoi  PHY111      52.57           60.92
46     Hemakshi Kumawat  CHM113      42.16             NaN
47             Siva Sai  MTH111      69.38           64.66
48          Aanya Nayak  LIF111      59.00           59.79
49     Hemakshi Kumawat  CHM112      53.90           52.37
50        Kritika Singh  CHM113      82.02           77.36
51     Nikhil Prajapati  LIF111      64.46           51.66
52              Sujal S  MTH113        NaN           62.20
53       Manisha Rathod  ELC111      53.87           64.12
54       Siddharth Soni   TA111      47.15             NaN
55         Prince Singh  CHM112      69.89           26.08
56         Rachna Sinha  ELC112      44.95           45.42
57             Siva Sai  MTH112      60.24           59.78
58        Krish Agarwal  ESC111      64.99           86.01
59       Aryaman Oberoi  PHY112      60.97           77.84
60       Parth Parashar  LIF111      52.81           57.67
61       Riddhi Shingte  MTH113      86.35           89.75
62     Nikhil Prajapati  MTH112      52.65             NaN
63       Riddhi Shingte  PHY115      77.62           35.66
64                  NaN  MTH112      41.68           48.54
65       Kanishk Sharma  PHY113      73.12           60.88
66          Dipon Konar  MTH113      71.42           84.23
67      Harshit Karnani   TA111      43.12           77.72
68         Rachna Sinha  CHM113      53.63           88.24
69       Parth Parashar  CHM113      45.49           88.19
70        Krish Agarwal  PHY111      57.13             NaN
71         Anusha Gupta  ELC113      43.74           55.78
72       Aryaman Oberoi  MTH111      64.74           83.51
73       Kanishk Sharma  PHY111      50.26           25.26
74          Anurag Sahu  ELC111      59.17           88.90
75          Sejal Dubey   TA111      74.42           73.35
76          Sejal Dubey  PHY114        NaN           86.84
77          Dipon Konar  ELC112      78.79           78.94
78       Aryaman Oberoi  LIF111      72.21             NaN
79       Siddharth Soni  MTH113      72.99           25.31
80         Prince Singh  MTH111      75.16           55.37
81         Pratik Maity  PHY115      49.42           83.63
82       Siddharth Soni     NaN      68.78           76.60
83             Mitanshi   TA111      87.97           46.36
84   Praneel iralapalle  ELC113      58.79           25.97
85          Sneha Patra  ELC111      70.39           28.88
86             Siva Sai  PHY112      43.56           42.08
87         Prince Singh  ELC112      71.96           37.96
88     Nikhil Prajapati  MTH114      49.86           21.74
89       Aryaman Oberoi  CHM111      49.25           70.27
90          Ashma Singh  LIF111      79.95           52.27
91         Anurag Patil  ELC112      79.87           39.82
92     Hemakshi Kumawat  CHM113        NaN           44.63
93          Sejal Dubey  MTH114      63.68           20.77
94          Sneha Patra  PHY114      73.76             NaN
95          Sneha Patra  PHY115      56.87           73.33
96                  NaN  ELC113      70.50           40.53
97          Aanya Nayak  ELC111      73.95           71.02
98      Harshit Karnani  PHY112      47.84           27.07
99      Utham Teja Sree   TA111      49.55           74.03
100        Anusha Gupta  LIF111      81.81           29.97
101     Harshit Karnani  MTH113      77.69           41.93
102    Nikhil Prajapati  MTH112      85.30             NaN
103            Siva Sai  LIF111      60.65           85.21
104                 NaN  ESC112      82.64           62.53
105      Aryaman Oberoi  CHM112      41.04           69.07
106      Aryaman Oberoi  MTH113      58.19           64.25
107      Riddhi Shingte  LIF111      81.25           62.40
108      Ketan Aggarwal  CHM111      79.50           61.29
109         Dipon Konar  MTH112      40.90           43.72
110      Riddhi Shingte  MTH112      88.31           37.56
111    Nikhil Prajapati  CHM111      84.12           46.20
112                 NaN  ELC112      44.40           89.77
113            Siva Sai  ELC111      60.39           58.39
114      Kanishk Sharma  CHM113      74.39           48.53
115         Sejal Dubey  PHY115      64.29           82.87
116             Sujal S  MTH111        NaN           82.64
117         Aanya Nayak  MTH112      57.27           44.78
118      Siddharth Soni  ESC112      82.20           67.40
119         Anurag Sahu  PHY114      64.79           61.49
120                 NaN  ELC111      81.93           51.83
121       Kritika Singh  ESC111      78.57           89.35
122      Manisha Rathod  PHY112      57.51           69.26
123  Praneel iralapalle  CHM112      64.18           67.57
124         Ashma Singh  CHM111        NaN           83.13
125         Anurag Sahu  MTH111      51.98           63.63
126         Ashma Singh  PHY111      65.83             NaN
127            Mitanshi  ESC111      48.76           61.07
128                 NaN  ELC112      53.41           71.69
129       Kritika Singh  ELC113      56.92           43.67
130         Sejal Dubey  MTH113      88.03           38.74
131              Chhaya  MTH111      68.47           52.37
132       Kritika Singh  PHY111        NaN           43.60
133     Utham Teja Sree  MTH113      41.74           29.69
134    Nikhil Prajapati  MTH112      43.48             NaN
135         Sejal Dubey  PHY114      71.60           76.71
136         Ashma Singh  PHY111      68.56           32.76
137             Sujal S  PHY115      84.79           27.42
138       Kritika Singh  ESC112      69.65           73.83
139      Riddhi Shingte  CHM113      86.30           54.25
140       Krish Agarwal  MTH112        NaN           82.76
141      Parth Parashar  CHM111      58.07           23.17
142         Ashma Singh  MTH114      57.33             NaN
143  Praneel iralapalle  PHY114      56.27           46.74
144        Prince Singh  MTH114      88.53           49.96
145         Anurag Sahu  ELC112      43.64           62.31
146       Kritika Singh  PHY111      56.36           30.21
147         Dipon Konar  ELC111      55.12           82.84
148      Parth Parashar   TA111        NaN           77.04
149         Gungun Jain  CHM111      56.66           54.76
150    Hemakshi Kumawat  ELC111      57.83           84.46
151      Aryaman Oberoi  PHY113      51.80           71.06
152                 NaN  ELC111      79.69           42.61
153         Aanya Nayak  PHY112      56.37           37.89
154    Nikhil Prajapati   TA111      57.57           23.68
155         Aanya Nayak  PHY113      46.03           47.37
156         Ashma Singh  MTH114      59.03           43.84
157      Kanishk Sharma  ELC112      68.54           79.32
158              Chhaya  PHY113      78.96           78.29
159         Sejal Dubey  ESC111      79.49           26.93
160                 NaN  CHM112      69.62           46.49
161      Riddhi Shingte  LIF111      81.14           82.83
162      Riddhi Shingte  ELC113      76.75           67.95
163              Chhaya  MTH114      85.38           54.22
164        Rachna Sinha  MTH114        NaN           64.24
165         Gungun Jain  MTH113      79.62           85.98
166      Riddhi Shingte  PHY111      56.07             NaN
167     Utham Teja Sree  PHY111      84.87           33.66
168                 NaN  PHY112      65.06           55.76
169       Krish Agarwal  ESC112      83.04           52.62
170              Chhaya  PHY114      53.47           50.56
171         Anurag Sahu  MTH111      51.60           33.57
172         Anurag Sahu  MTH113      64.05           41.76
173        Anusha Gupta  CHM111      40.65           74.51
174    Nikhil Prajapati  PHY115      75.28           68.80
175         Aanya Nayak  MTH111      43.44           75.50
176      Riddhi Shingte  LIF111      75.39           62.85
177      Siddharth Soni  MTH113      75.37           20.08
178       Kritika Singh  ELC112      55.69           63.97
179              Chhaya  MTH112      64.57           55.43
180     Utham Teja Sree  LIF111      67.58           34.19
181      Manisha Rathod  MTH113      87.29           31.30
182        Anurag Patil  ELC113      54.81             NaN
183     Harshit Karnani  MTH111      57.90           71.48
184                 NaN  CHM113      58.81           59.50
185         Sejal Dubey  PHY113      66.96           74.16
186      Aryaman Oberoi  ESC111      87.11           66.38
187         Gungun Jain  ELC111      56.26           30.43
188              Chhaya  MTH114        NaN           42.26
189         Aanya Nayak  ESC112      82.42           84.12
190     Utham Teja Sree  MTH113      55.36             NaN
191         Gungun Jain  ESC111      77.56           88.57
192                 NaN  ELC113      66.65           63.00
193        Pratik Maity  MTH114      55.83           32.23
194        Prince Singh  ELC113      42.18           62.39
195       Kritika Singh  ELC112      68.57           77.98
196     Harshit Karnani  PHY112      52.31           35.75
197         Sneha Patra  PHY113      58.98           21.98
198         Ashma Singh  PHY111      88.56           82.63
199      Parth Parashar  PHY115      80.52           42.89

In [6]:
print(df.isnull())

     Student Name  Course  Marks (%)  Attendance (%)
0           False   False      False           False
1           False   False      False           False
2           False   False      False           False
3           False   False      False           False
4           False   False      False           False
..            ...     ...        ...             ...
195         False   False      False           False
196         False   False      False           False
197         False   False      False           False
198         False   False      False           False
199         False   False      False           False

[200 rows x 4 columns]

In [7]:
new_df = df.dropna(subset=['Student Name'])

In [8]:
print(new_df)

         Student Name  Course  Marks (%)  Attendance (%)
0         Dipon Konar  ELC111      56.72           63.08
1      Parth Parashar  PHY113      84.59           20.96
2         Anurag Sahu  MTH113      41.13           59.86
3    Hemakshi Kumawat  CHM112      59.43           57.34
4      Parth Parashar  ELC111      62.88           30.82
..                ...     ...        ...             ...
195     Kritika Singh  ELC112      68.57           77.98
196   Harshit Karnani  PHY112      52.31           35.75
197       Sneha Patra  PHY113      58.98           21.98
198       Ashma Singh  PHY111      88.56           82.63
199    Parth Parashar  PHY115      80.52           42.89

[188 rows x 4 columns]

In [10]:
numerical_columns = ['Marks (%)','Attendence (%)']

In [12]:
def geometric_mean(a, b):
    if a > 0 and b > 0:  
        return np.sqrt(a * b)
    return np.nan

In [16]:
for column in numerical_columns:
    for i in range(1, len(new_df) - 1):  
        if pd.isnull(new_df[column].iloc[i]): 
            previous_value = bew_df[column].iloc[i - 1]
            next_value = new_df[column].iloc[i + 1]
            
            new_df[column].iloc[i] = geometric_mean(previous_value, next_value)

KeyError: 'Marks'

In [17]:
new_df.to_csv('cleaned_IITK_Courses_Report.csv')